### ISSUE TITLE
Installable from web for mobile

### ISSUE THREAD

**Issue by sectore** [elsirion/webimint-rs#34]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable

Example https://microsoftedge.github.io/Demos/pwamp/

**Comment by elsirion** [comment]
I added a `manifest.json` in #45, but that doesn't seem to be enough. One apparently needs to spawn a service worker after all. The good news: leptos-use has something prepared https://github.com/Synphonyte/leptos-use/tree/main/examples/use_service_worker
